[package]
name = "app"
version = "0.1.0"
description = "ReadAny - AI-powered EPUB Reader"
authors = ["you"]
edition = "2021"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
tauri-plugin-http = "2"
rusqlite = { version = "0.31", features = ["bundled"] }
anyhow = "1"
serde_json = "1"
tauri-plugin-websocket = "2"
